---
- name: jenkins ansible deployment
  hosts: agentnode
  become: yes

  tasks:
    - name: run docker container
      docker_container: name=con1 , image=nginx:latest tty=true state=started ports=8080:80
