---
- name: jenkins ansible deployment
  hosts: all
  become: yes
  tasks:
    - name: docker container run
      docker_container:
        name=ansiblecon image=nginx:latest state=started tty=true ports=["8080:80"]
