---
- name: jenkins ansible deployment
  hosts: all
  become: true

  tasks:
   - name: docker container run
     docker_container:
       name=ansiblecon
       image=nginx:latest
       tty=true
       state=started
       ports=["8080:80"]
